# 🚀 GPT

<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/rickiepark/Generative_Deep_Learning_2nd_Edition/blob/main/notebooks/09_transformer/gpt/gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

이 노트북에서는 와인 리뷰 데이터셋으로 GPT 모델을 훈련합니다.

이 코드는 케라스 웹사이트에 있는 Apoorv Nandan이 만든 훌륭한 [GPT 튜토리얼](https://keras.io/examples/generative/text_generation_with_miniature_gpt/)을 참고했습니다.

In [1]:
import numpy as np
import json
import re
import string
from IPython.display import display, HTML

import tensorflow as tf
from tensorflow.keras import layers, models, losses, callbacks

## 0. 파라미터 <a name="parameters"></a>

In [2]:
VOCAB_SIZE = 10000
MAX_LEN = 80
EMBEDDING_DIM = 256
KEY_DIM = 256
N_HEADS = 2
FEED_FORWARD_DIM = 256
VALIDATION_SPLIT = 0.2
SEED = 42
LOAD_MODEL = False
BATCH_SIZE = 32
EPOCHS = 5

## 1. 데이터 로드 <a name="load"></a>

In [3]:
import sys

# 코랩일 경우 노트북에서 celeba 데이터셋을 받습니다.
if 'google.colab' in sys.modules:
    # 캐글-->Setttings-->API-->Create New Token에서
    # kaggle.json 파일을 만들어 코랩에 업로드하세요.
    from google.colab import files
    files.upload()
    !mkdir ~/.kaggle
    !cp kaggle.json ~/.kaggle/
    !chmod 600 ~/.kaggle/kaggle.json
    # celeba 데이터셋을 다운로드하고 압축을 해제합니다.
    !kaggle datasets download -d zynicide/wine-reviews
    !unzip -q wine-reviews.zip
    # model 디렉토리를 만듭니다.
    !mkdir models

Saving kaggle.json to kaggle.json
 65% 33.0M/50.9M [00:00<00:00, 120MB/s] 
100% 50.9M/50.9M [00:00<00:00, 127MB/s]


In [4]:
# 전체 데이터셋 로드
with open("./winemag-data-130k-v2.json") as json_data:
    wine_data = json.load(json_data)

In [5]:
wine_data[10]

{'points': '87',
 'title': 'Kirkland Signature 2011 Mountain Cuvée Cabernet Sauvignon (Napa Valley)',
 'description': 'Soft, supple plum envelopes an oaky structure in this Cabernet, supported by 15% Merlot. Coffee and chocolate complete the picture, finishing strong at the end, resulting in a value-priced wine of attractive flavor and immediate accessibility.',
 'taster_name': 'Virginie Boone',
 'taster_twitter_handle': '@vboone',
 'price': 19,
 'designation': 'Mountain Cuvée',
 'variety': 'Cabernet Sauvignon',
 'region_1': 'Napa Valley',
 'region_2': 'Napa',
 'province': 'California',
 'country': 'US',
 'winery': 'Kirkland Signature'}

In [6]:
# 데이터셋 필터링
filtered_data = [
    "wine review : "
    + x["country"]
    + " : "
    + x["province"]
    + " : "
    + x["variety"]
    + " : "
    + x["description"]
    for x in wine_data
    if x["country"] is not None
    and x["province"] is not None
    and x["variety"] is not None
    and x["description"] is not None
]

In [7]:
# 레시피 개수 카운트
n_wines = len(filtered_data)
print(f"{n_wines}개 레시피 로드")

129907개 레시피 로드


In [8]:
example = filtered_data[25]
print(example)

wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard-designated Pinot that hails from a high-elevation site. Small in production, it offers intense, full-bodied raspberry and blackberry steeped in smoky spice and smooth texture.


## 2. 데이터 토큰화 <a name="tokenize"></a>

In [9]:
# 구두점 앞에 공백을 채워서 별도의 '단어'로 취급합니다.
def pad_punctuation(s):
    s = re.sub(f"([{string.punctuation}, '\n'])", r" \1 ", s)
    s = re.sub(" +", " ", s)
    return s


text_data = [pad_punctuation(x) for x in filtered_data]

In [10]:
# 레시피 예시 표시
example_data = text_data[25]
example_data

'wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard - designated Pinot that hails from a high - elevation site . Small in production , it offers intense , full - bodied raspberry and blackberry steeped in smoky spice and smooth texture . '

In [11]:
# 텐서플로 데이터셋으로 변환하기
text_ds = (
    tf.data.Dataset.from_tensor_slices(text_data)
    .batch(BATCH_SIZE)
    .shuffle(1000)
)

In [12]:
# TextVectorization 층 만들기
vectorize_layer = layers.TextVectorization(
    standardize="lower",
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=MAX_LEN + 1,
)

In [13]:
# 훈련 세트에 이 층을 적용합니다.
vectorize_layer.adapt(text_ds)
vocab = vectorize_layer.get_vocabulary()

In [14]:
# 토큰:단어 매핑 표시
for i, word in enumerate(vocab[:10]):
    print(f"{i}: {word}")

0: 
1: [UNK]
2: :
3: ,
4: .
5: and
6: the
7: wine
8: a
9: of


In [15]:
# 동일한 샘플을 정수로 변환하여 표시
example_tokenised = vectorize_layer(example_data)
print(example_tokenised.numpy())

[   7   10    2   20    2   29    2   43   62    2   55    5  243 4145
  453  634   26    9  497  499  667   17   12  142   14 2214   43   25
 2484   32    8  223   14 2213  948    4  594   17  987    3   15   75
  237    3   64   14   82   97    5   74 2633   17  198   49    5  125
   77    4    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0]


## 3. 훈련 세트 생성 <a name="create"></a>

In [16]:
# 레시피 텍스트와 한 단어만큼 이동된 동일한 텍스트로 훈련 세트를 만듭니다.
def prepare_inputs(text):
    text = tf.expand_dims(text, -1)
    tokenized_sentences = vectorize_layer(text)
    x = tokenized_sentences[:, :-1]
    y = tokenized_sentences[:, 1:]
    return x, y


train_ds = text_ds.map(prepare_inputs)

In [17]:
example_input_output = train_ds.take(1).get_single_element()

In [18]:
# 입력 예시
example_input_output[0][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([   7,   10,    2,   42,    2,  344,    2,  119,    2,   95,    5,
       2040,   39, 5342,   88,   23,    6,   60,    4,    6,   28,   83,
       1135,  648,    5,  372,  664,   93,    3,   56,    5,   38,  361,
         19,    6, 1718,    4,    6,  285,   13,   76,    5,  997,   33,
       2542,   11,  195,    4,    6,   31,   13,  155,    5, 1073,   11,
        401,   95,    4,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

In [19]:
# 출력 예시(토큰 하나씩 이동)
example_input_output[1][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([  10,    2,   42,    2,  344,    2,  119,    2,   95,    5, 2040,
         39, 5342,   88,   23,    6,   60,    4,    6,   28,   83, 1135,
        648,    5,  372,  664,   93,    3,   56,    5,   38,  361,   19,
          6, 1718,    4,    6,  285,   13,   76,    5,  997,   33, 2542,
         11,  195,    4,    6,   31,   13,  155,    5, 1073,   11,  401,
         95,    4,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0])>

## 5. 코잘 어텐션 마스킹 함수 만들기 <a name="causal"></a>

In [20]:
def causal_attention_mask(batch_size, n_dest, n_src, dtype):
    i = tf.range(n_dest)[:, None]
    j = tf.range(n_src)
    m = i >= j - n_src + n_dest
    mask = tf.cast(m, dtype)
    mask = tf.reshape(mask, [1, n_dest, n_src])
    mult = tf.concat(
        [tf.expand_dims(batch_size, -1), tf.constant([1, 1], dtype=tf.int32)], 0
    )
    return tf.tile(mask, mult)


np.transpose(causal_attention_mask(1, 10, 10, dtype=tf.int32)[0])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

## 6. 트랜스포머 블록 층 만들기 <a name="transformer"></a>

In [21]:
class TransformerBlock(layers.Layer):
    def __init__(self, num_heads, key_dim, embed_dim, ff_dim, dropout_rate=0.1):
        super(TransformerBlock, self).__init__()
        self.num_heads = num_heads
        self.key_dim = key_dim
        self.embed_dim = embed_dim
        self.ff_dim = ff_dim
        self.dropout_rate = dropout_rate
        self.attn = layers.MultiHeadAttention(
            num_heads, key_dim, output_shape=embed_dim
        )
        self.dropout_1 = layers.Dropout(self.dropout_rate)
        self.ln_1 = layers.LayerNormalization(epsilon=1e-6)
        self.ffn_1 = layers.Dense(self.ff_dim, activation="relu")
        self.ffn_2 = layers.Dense(self.embed_dim)
        self.dropout_2 = layers.Dropout(self.dropout_rate)
        self.ln_2 = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size = input_shape[0]
        seq_len = input_shape[1]
        causal_mask = causal_attention_mask(
            batch_size, seq_len, seq_len, tf.bool
        )
        attention_output, attention_scores = self.attn(
            inputs,
            inputs,
            attention_mask=causal_mask,
            return_attention_scores=True,
        )
        attention_output = self.dropout_1(attention_output)
        out1 = self.ln_1(inputs + attention_output)
        ffn_1 = self.ffn_1(out1)
        ffn_2 = self.ffn_2(ffn_1)
        ffn_output = self.dropout_2(ffn_2)
        return (self.ln_2(out1 + ffn_output), attention_scores)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "key_dim": self.key_dim,
                "embed_dim": self.embed_dim,
                "num_heads": self.num_heads,
                "ff_dim": self.ff_dim,
                "dropout_rate": self.dropout_rate,
            }
        )
        return config

## 7. 토큰 임베딩과 위치 인코딩 만들기 <a name="embedder"></a>

In [22]:
class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, max_len, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.max_len = max_len
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.token_emb = layers.Embedding(
            input_dim=vocab_size, output_dim=embed_dim
        )
        self.pos_emb = layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "max_len": self.max_len,
                "vocab_size": self.vocab_size,
                "embed_dim": self.embed_dim,
            }
        )
        return config

## 8. 트랜스포머 모델 만들기 <a name="transformer_decoder"></a>

In [23]:
inputs = layers.Input(shape=(None,), dtype=tf.int32)
x = TokenAndPositionEmbedding(MAX_LEN, VOCAB_SIZE, EMBEDDING_DIM)(inputs)
x, attention_scores = TransformerBlock(
    N_HEADS, KEY_DIM, EMBEDDING_DIM, FEED_FORWARD_DIM
)(x)
outputs = layers.Dense(VOCAB_SIZE, activation="softmax")(x)
gpt = models.Model(inputs=inputs, outputs=[outputs, attention_scores])
gpt.compile("adam", loss=[losses.SparseCategoricalCrossentropy(), None])

In [24]:
gpt.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None)]            0         
                                                                 
 token_and_position_embeddi  (None, None, 256)         2580480   
 ng (TokenAndPositionEmbedd                                      
 ing)                                                            
                                                                 
 transformer_block (Transfo  ((None, None, 256),       658688    
 rmerBlock)                   (None, 2, None, None))             
                                                                 
 dense_2 (Dense)             (None, None, 10000)       2570000   
                                                                 
Total params: 5809168 (22.16 MB)
Trainable params: 5809168 (22.16 MB)
Non-trainable params: 0 (0.00 Byte)
_____________________

In [25]:
if LOAD_MODEL:
    # model.load_weights('./models/model')
    gpt = models.load_model("./models/gpt", compile=True)

## 9. 트랜스포머 훈련하기 <a name="train"></a>

In [26]:
# TextGenerator 체크포인트 만들기
class TextGenerator(callbacks.Callback):
    def __init__(self, index_to_word, top_k=10):
        self.index_to_word = index_to_word
        self.word_to_index = {
            word: index for index, word in enumerate(index_to_word)
        }

    def sample_from(self, probs, temperature):
        probs = probs ** (1 / temperature)
        probs = probs / np.sum(probs)
        return np.random.choice(len(probs), p=probs), probs

    def generate(self, start_prompt, max_tokens, temperature):
        start_tokens = [
            self.word_to_index.get(x, 1) for x in start_prompt.split()
        ]
        sample_token = None
        info = []
        while len(start_tokens) < max_tokens and sample_token != 0:
            x = np.array([start_tokens])
            y, att = self.model.predict(x, verbose=0)
            sample_token, probs = self.sample_from(y[0][-1], temperature)
            info.append(
                {
                    "prompt": start_prompt,
                    "word_probs": probs,
                    "atts": att[0, :, -1, :],
                }
            )
            start_tokens.append(sample_token)
            start_prompt = start_prompt + " " + self.index_to_word[sample_token]
        print(f"\n생성된 텍스트:\n{start_prompt}\n")
        return info

    def on_epoch_end(self, epoch, logs=None):
        self.generate("wine review", max_tokens=80, temperature=1.0)

In [27]:
# 모델 저장 체크포인트 만들기
model_checkpoint_callback = callbacks.ModelCheckpoint(
    filepath="./checkpoint/checkpoint.ckpt",
    save_weights_only=True,
    save_freq="epoch",
    verbose=0,
)

tensorboard_callback = callbacks.TensorBoard(log_dir="./logs")

# 시작 프롬프트 토큰화
text_generator = TextGenerator(vocab)

In [28]:
gpt.fit(
    train_ds,
    epochs=EPOCHS,
    callbacks=[model_checkpoint_callback, tensorboard_callback, text_generator],
)

Epoch 1/5
4059/4060 [============================>.] - ETA: 0s - loss: 2.2547 - dense_2_loss: 2.2547
생성된 텍스트:
wine review : us : oregon : pinot noir : a tightly wound , layered mix of black and ripe , seemingly dissipate . the palate combines earthy , drying tannins with the tart red plum fruit , and licorice emerging emerging upon a savory streak of graphite that follows the extended finish . 

4060/4060 [==============================] - 155s 36ms/step - loss: 2.2546 - dense_2_loss: 2.2546
Epoch 2/5
4060/4060 [==============================] - ETA: 0s - loss: 1.9603 - dense_2_loss: 1.9603
생성된 텍스트:
wine review : us : california : syrah : the dense aroma comes from this as well - made , smooth and soft in fruit flavor with a gentle texture of plummy raspberries , peppercorns , tapenade and cedar . its touches of cassis and tannic structure enhance the juicy blackberries to all the fruit nicely seasoned with cinnamon . chardonnay . would be full bodied or expressive at first it should b

In [29]:
# 최종 모델 저장
gpt.save("./models/gpt")

# 3. 트랜스포머를 사용하여 텍스트 생성

In [30]:
def print_probs(info, vocab, top_k=5):
    for i in info:
        highlighted_text = []
        for word, att_score in zip(
            i["prompt"].split(), np.mean(i["atts"], axis=0)
        ):
            highlighted_text.append(
                '<span style="background-color:rgba(135,206,250,'
                + str(att_score / max(np.mean(i["atts"], axis=0)))
                + ');">'
                + word
                + "</span>"
            )
        highlighted_text = " ".join(highlighted_text)
        display(HTML(highlighted_text))

        word_probs = i["word_probs"]
        p_sorted = np.sort(word_probs)[::-1][:top_k]
        i_sorted = np.argsort(word_probs)[::-1][:top_k]
        for p, i in zip(p_sorted, i_sorted):
            print(f"{vocab[i]}:   \t{np.round(100*p,2)}%")
        print("--------\n")

In [31]:
info = text_generator.generate(
    "wine review : us", max_tokens=80, temperature=1.0
)


생성된 텍스트:
wine review : us : oregon : pinot noir : aromatically , this is a low alcohol ( 30 % ) wine . the wine is sleek and fruity , with notes of red cherry and plenty of sweet raspberry and strawberry . spicy and cherry flavors gain extra complexity within a frame of barrel wax , white pepper around that just a hint of coconut on the midpalate . 



In [32]:
info = text_generator.generate(
    "wine review : italy", max_tokens=80, temperature=0.5
)


생성된 텍스트:
wine review : italy : northeastern italy : pinot grigio : [UNK] ' s [UNK] ' s wine ' s fresh and crisp , with an intense bouquet of honey , peach and apricot . the wine is light and silky , with a bright , crisp feel in the mouth . 



In [33]:
info = text_generator.generate(
    "wine review : germany", max_tokens=80, temperature=0.5
)
print_probs(info, vocab)


생성된 텍스트:
wine review : germany : baden : spätburgunder : smoke and smoke notes lend a savory , savory tone to this pinot noir . the palate is a bit sharp and unrefined , but ripe and juicy , with black cherry and plum flavors . finishes with a zesty , but clean . 



::   	100.0%
-:   	0.0%
africa:   	0.0%
grosso:   	0.0%
blend:   	0.0%
--------



mosel:   	97.52%
nahe:   	0.64%
baden:   	0.54%
rheingau:   	0.44%
rheinhessen:   	0.36%
--------



::   	100.0%
grosso:   	0.0%
other:   	0.0%
[UNK]:   	0.0%
-:   	0.0%
--------



pinot:   	79.94%
spätburgunder:   	19.76%
[UNK]:   	0.11%
riesling:   	0.08%
sparkling:   	0.03%
--------



::   	100.0%
blanc:   	0.0%
-:   	0.0%
grosso:   	0.0%
noir:   	0.0%
--------



this:   	21.39%
a:   	18.61%
hints:   	12.9%
whiffs:   	5.46%
the:   	5.11%
--------



and:   	81.77%
,:   	17.44%
seeps:   	0.77%
notes:   	0.02%
tones:   	0.01%
--------



char:   	57.92%
spice:   	10.43%
bramble:   	9.46%
toast:   	5.73%
crushed:   	2.37%
--------



notes:   	65.47%
aromas:   	15.08%
tones:   	7.2%
lend:   	3.14%
are:   	1.92%
--------



lend:   	80.72%
add:   	9.51%
accent:   	3.05%
are:   	2.33%
on:   	1.11%
--------



a:   	88.13%
an:   	6.17%
savory:   	2.88%
complexity:   	1.49%
nuance:   	0.28%
--------



savory:   	97.33%
woodsy:   	0.8%
rustic:   	0.42%
savoriness:   	0.42%
pretty:   	0.14%
--------



,:   	87.66%
tone:   	7.59%
edge:   	3.24%
character:   	0.28%
profile:   	0.19%
--------



savory:   	83.21%
earthy:   	3.63%
bramble:   	3.05%
woodsy:   	2.55%
black:   	1.17%
--------



tone:   	50.23%
,:   	36.93%
edge:   	4.59%
profile:   	3.51%
nose:   	1.99%
--------



to:   	100.0%
of:   	0.0%
in:   	0.0%
that:   	0.0%
on:   	0.0%
--------



this:   	77.68%
ripe:   	6.36%
black:   	3.95%
fresh:   	3.95%
the:   	2.47%
--------



wine:   	25.36%
full:   	22.82%
pinot:   	14.1%
bold:   	7.53%
ripe:   	4.54%
--------



noir:   	98.23%
.:   	0.83%
,:   	0.72%
that:   	0.17%
is:   	0.02%
--------



.:   	90.65%
,:   	8.67%
that:   	0.44%
from:   	0.08%
rosé:   	0.04%
--------



it:   	41.68%
the:   	35.94%
black:   	3.81%
tart:   	2.57%
while:   	1.92%
--------



palate:   	99.16%
wine:   	0.45%
flavors:   	0.1%
cherry:   	0.05%
cranberry:   	0.05%
--------



is:   	98.76%
offers:   	0.65%
boasts:   	0.2%
has:   	0.18%
shows:   	0.09%
--------



juicy:   	24.1%
fresh:   	8.64%
brisk:   	6.28%
bright:   	5.73%
dry:   	5.37%
--------



bit:   	95.74%
shade:   	1.57%
bold:   	0.37%
refreshingly:   	0.37%
bright:   	0.15%
--------



lean:   	44.57%
thin:   	8.15%
soft:   	6.8%
sour:   	5.07%
tart:   	4.65%
--------



,:   	42.37%
in:   	34.5%
and:   	20.37%
on:   	1.91%
with:   	0.33%
--------



acidic:   	52.8%
tart:   	10.75%
angular:   	8.26%
edgy:   	3.87%
astringent:   	3.3%
--------



,:   	90.03%
.:   	9.91%
in:   	0.02%
now:   	0.02%
on:   	0.01%
--------



but:   	57.95%
with:   	40.9%
yet:   	0.35%
and:   	0.3%
offering:   	0.18%
--------



the:   	15.55%
not:   	11.89%
ripe:   	9.0%
slightly:   	7.6%
brisk:   	6.11%
--------



,:   	41.63%
and:   	24.68%
with:   	17.41%
.:   	4.67%
in:   	3.95%
--------



juicy:   	31.13%
sour:   	17.22%
savory:   	12.76%
brambly:   	5.03%
tart:   	4.01%
--------



.:   	49.71%
,:   	33.69%
with:   	11.13%
in:   	2.18%
on:   	2.13%
--------



with:   	90.82%
boasting:   	2.96%
finishing:   	1.82%
offering:   	1.47%
but:   	0.55%
--------



a:   	54.17%
black:   	24.31%
flavors:   	4.85%
cranberry:   	2.26%
fresh:   	1.82%
--------



cherry:   	91.0%
-:   	5.65%
plum:   	2.75%
cherries:   	0.4%
raspberry:   	0.07%
--------



and:   	96.0%
flavors:   	2.61%
,:   	0.64%
fruit:   	0.46%
-:   	0.14%
--------



plum:   	74.06%
raspberry:   	9.06%
cranberry:   	6.41%
berry:   	2.84%
blackberry:   	2.5%
--------



flavors:   	99.61%
fruit:   	0.23%
notes:   	0.08%
flavor:   	0.02%
skin:   	0.01%
--------



.:   	95.78%
accented:   	2.56%
that:   	0.5%
,:   	0.41%
and:   	0.3%
--------



finishes:   	61.67%
it:   	22.46%
the:   	6.13%
:   	2.75%
drink:   	1.45%
--------



with:   	86.43%
long:   	4.53%
moderately:   	2.21%
brisk:   	1.1%
a:   	0.94%
--------



a:   	99.35%
an:   	0.21%
hints:   	0.06%
some:   	0.05%
notes:   	0.04%
--------



touch:   	21.8%
bit:   	16.89%
hint:   	15.08%
long:   	8.51%
whisper:   	6.27%
--------



,:   	72.82%
acidity:   	7.55%
lime:   	4.7%
note:   	3.15%
lemon:   	2.3%
--------



bright:   	30.1%
clean:   	12.51%
slightly:   	7.95%
brisk:   	6.36%
fresh:   	4.45%
--------



brisk:   	17.17%
slightly:   	10.68%
a:   	8.37%
elegant:   	6.17%
fresh:   	5.36%
--------



,:   	53.27%
and:   	39.67%
finish:   	2.68%
acidity:   	1.45%
-:   	0.79%
--------



:   	98.11%
drink:   	1.7%
a:   	0.06%
it:   	0.04%
the:   	0.02%
--------

